# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import showtime_pb2 as showtime__pb2


class ShowtimesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShowTimes = channel.unary_stream(
                '/Showtimes/GetShowTimes',
                request_serializer=showtime__pb2.Empty.SerializeToString,
                response_deserializer=showtime__pb2.ShowTime.FromString,
                )
        self.GetShowTimeByDate = channel.unary_unary(
                '/Showtimes/GetShowTimeByDate',
                request_serializer=showtime__pb2.Date.SerializeToString,
                response_deserializer=showtime__pb2.ShowTime.FromString,
                )


class ShowtimesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetShowTimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShowTimeByDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShowtimesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShowTimes': grpc.unary_stream_rpc_method_handler(
                    servicer.GetShowTimes,
                    request_deserializer=showtime__pb2.Empty.FromString,
                    response_serializer=showtime__pb2.ShowTime.SerializeToString,
            ),
            'GetShowTimeByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShowTimeByDate,
                    request_deserializer=showtime__pb2.Date.FromString,
                    response_serializer=showtime__pb2.ShowTime.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Showtimes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Showtimes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetShowTimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Showtimes/GetShowTimes',
            showtime__pb2.Empty.SerializeToString,
            showtime__pb2.ShowTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetShowTimeByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Showtimes/GetShowTimeByDate',
            showtime__pb2.Date.SerializeToString,
            showtime__pb2.ShowTime.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
