# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import booking_pb2 as booking__pb2


class BookingsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookings = channel.unary_stream(
                '/Bookings/GetBookings',
                request_serializer=booking__pb2.EmptyBooking.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                )
        self.GetBookingsByUser = channel.unary_unary(
                '/Bookings/GetBookingsByUser',
                request_serializer=booking__pb2.Id.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                )
        self.PostNewBooking = channel.unary_unary(
                '/Bookings/PostNewBooking',
                request_serializer=booking__pb2.PostBooking.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                )
        self.PostNewBookingUser = channel.unary_unary(
                '/Bookings/PostNewBookingUser',
                request_serializer=booking__pb2.Id.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                )


class BookingsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookingsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostNewBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostNewBookingUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookings': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBookings,
                    request_deserializer=booking__pb2.EmptyBooking.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'GetBookingsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookingsByUser,
                    request_deserializer=booking__pb2.Id.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'PostNewBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.PostNewBooking,
                    request_deserializer=booking__pb2.PostBooking.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'PostNewBookingUser': grpc.unary_unary_rpc_method_handler(
                    servicer.PostNewBookingUser,
                    request_deserializer=booking__pb2.Id.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Bookings', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bookings(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Bookings/GetBookings',
            booking__pb2.EmptyBooking.SerializeToString,
            booking__pb2.Booking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBookingsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bookings/GetBookingsByUser',
            booking__pb2.Id.SerializeToString,
            booking__pb2.Booking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostNewBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bookings/PostNewBooking',
            booking__pb2.PostBooking.SerializeToString,
            booking__pb2.Booking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostNewBookingUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bookings/PostNewBookingUser',
            booking__pb2.Id.SerializeToString,
            booking__pb2.Booking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
